# Generated by Django 2.0.7 on 2018-08-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=128)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('invoice_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('project', models.ManyToManyField(to='projects.Project')),
            ],
        ),
    ]
