# Generated by Django 2.0.7 on 2018-09-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_remove_invoice_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-invoice_date']},
        ),
    ]
