"""
Django settings for HiredGun project.

Generated by 'django-admin startproject' using Django 2.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

# I used this tutorial for splitting the settings up into dev and prod:
# https://thinkster.io/tutorials/configuring-django-settings-for-production

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # 'projects.apps.ProjectsConfig',  # If I use this, static files don't work anymore :(
    'projects',
    'reports',
    'invoices',
    'profiles',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'HiredGun.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['./templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'HiredGun.wsgi.application'




# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'de-de'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Login stuff

LOGIN_REDIRECT_URL = '/'
# LOGOUT_REDIRECT_URL = '/'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

dbs = {
    'localfile': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, '../db.sqlite3'),
    },
    'dropbox': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': '/home/alexx/Dropbox/HiredGun.sqlite3',
    },
    'production': {
        # Store data in environment variables, not in public :)
        'ENGINE': os.getenv('HGUN_ENGINE'),
        'NAME': os.getenv('HGUN_DB'),
        'USER': os.getenv('HGUN_USER'),
        'PASSWORD': os.getenv('HGUN_PASS'),
        'HOST': os.getenv('HGUN_HOST'),
        'PORT': os.getenv('HGUN_PORT'),
    }
}

DATABASES = {
    'default': dbs['dropbox']
}


# Optional local settings (e.g. for no password validation)
# http://techstream.org/Bits/Local-Settings-in-django
try:
    from local_settings import *
except ImportError:
    pass
