# Generated by Django 2.0.7 on 2018-08-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='BIC',
            field=models.CharField(default='TODO please enter BIC', max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='IBAN',
            field=models.CharField(default='TODO please enter IBAN', max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_acct',
            field=models.CharField(default='TODO please enter bank account no', max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_sort_code',
            field=models.CharField(default='TODO please enter bank sort code', max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='paypal',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='TODO please enter phone no', max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='tax_id',
            field=models.CharField(default='TODO enter tax ID here', max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(default='TODO please enter address'),
        ),
    ]
