# Generated by Django 2.0.7 on 2018-12-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('side_income', '0002_sideproject_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sideproject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
