# Generated by Django 2.0.7 on 2018-08-12 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('invoice_email', models.EmailField(blank=True, max_length=256, null=True)),
                ('payment_terms', models.CharField(choices=[('Net 15', '15 days after invoice date'), ('Net 30', '30 days after invoice date'), ('21 MFI', '21st of the month following the invoice date'), ('2% 10 Net 30', '2% discount if payment received within ten days, otherwise Net 30'), ('COD', 'Cash on delivery'), ('PIA', 'Payment in advance')], default='Net 30', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('rate_unit', models.CharField(choices=[('hr', 'Hour'), ('day', 'Day'), ('fixed', 'Fixed')], default='hr', max_length=3)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('units_worked', models.DecimalField(decimal_places=2, max_digits=4)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('break_duration', models.DurationField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.Project')),
            ],
        ),
    ]
