# Generated by Django 2.0.7 on 2018-08-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='payment_terms',
            field=models.CharField(choices=[('Net 15', '15 days after invoice date'), ('Net 30', '30 days after invoice date'), ('21 MFI', '21st of the month following the invoice date'), ('2% 10 Net 30', '2% discount if payment received within ten days, otherwise Net 30'), ('COD', 'Cash on delivery'), ('PIA', 'Payment in advance')], default='Net 30', max_length=20),
        ),
    ]
