# Generated by Django 2.0.7 on 2018-08-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_session_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='rate_unit',
            field=models.CharField(choices=[('hr', 'Hour'), ('day', 'Day'), ('fix', 'Fixed')], default='hr', max_length=3),
        ),
    ]
