# Generated by Django 2.0.7 on 2018-08-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180803_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='units_worked',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='break_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
