# Generated by Django 2.0.7 on 2018-08-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180805_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='rate_unit',
            field=models.CharField(choices=[('hr', 'Hour'), ('day', 'Day'), ('fixed', 'Fixed')], default='hr', max_length=3),
        ),
    ]
