# Generated by Django 2.0.7 on 2018-08-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180805_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='billing_address',
            field=models.TextField(),
        ),
    ]
