# Generated by Django 2.1 on 2019-04-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180928_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimated_total_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
