# Generated by Django 2.0.7 on 2018-08-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20180805_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='billing_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
